### ISSUE TITLE
Support treesitter-based spell check on identifiers (var names, types etc).

### ISSUE THREAD

**Issue by pavkam** [ravibrock/spellwarn.nvim#3]
Also would be cool to have a small dictionary with common coding abbreviations and a minimum word size in these cases.

Not sure this falls into the scope of this plugin though.

**Comment by ravibrock** [comment]
Dictionary--I recommend [dirtytalk](https://github.com/psliwka/vim-dirtytalk).

Word size is outside of plugin scope, I think. The point is broadly to show diagnostics for spelling errors Neovim flagged regardless, and I don't want it to diverge too much from that. 

I was looking into adding support for other identifiers earlier today, though whether that's in plugin scope is questionable. More importantly (though I'm open to having my mind changed on this), I'm skeptical that it's a good idea given how many things like varnames are misspelled. Vim spellcheck doesn't pick up on "almost-words" like if I tried to say `local lsit = {}` instead of `local list = {}`. Rather, it just flags everything not in its dictionary, and when you consider how many variable names aren't (in my Luasnip config, for example, I have `local ls = require("luasnip")`) it seems there would be an unacceptably low signal:noise ratio for how many diagnostics are actually typos. The ideal solution would probably be something context aware that would check for typos in variables based on which variable names have been declared previously, but that would be its own project in and of itself, and would probably be better handled by something like a language server.

**Comment by ravibrock** [comment]
Closing this since I haven't heard back for a couple days and probably won't implement the changes suggested. Feel free to reopen or reply if you disagree with any aspects of my reasoning in the above response.
