### ISSUE TITLE
Add spelling for prints messages

### ISSUE THREAD

**Issue by crates51** [ravibrock/spellwarn.nvim#7]
I saw this on pycharm, would it be possible?

Example: `print("This is a wong message")`

**Comment by ravibrock** [comment]
Hi, maybe see #3 for a related issue. I'm not sure there's a good way to

- Get print statements in a relatively language agnostic way (I don't want to hardcode print statements in a bunch of languages, and treesitter would just pick up that it's a function)
- Integrate it with spellwarn in a way that doesn't diverge too much from the original purpose of essentially being a wrapper around native spellchecking
- Isolate the contents of the print statement in a language agnostic way (i.e. distinguishing between the contents of Python f-strings, C format strings, etc etc)

PRs always welcome if you would like to submit one, otherwise feel free to let me know if you disagree with any of the points I raised above and I'll be happy to reconsider it.
